import React from 'react'
import { GraphicSlide } from './GraphicSlide'
import { TableOfContents } from './TableOfContents'
import { Hello } from './slides/Hello'
import { TalkIsNot, TalkIs } from './slides/TalkIsNot'
import { WeirdTangent } from './slides/WeirdTangent'
import {
  Epistemology,
  EpistemologicalAttitude,
  TddStance,
  EpistemologyReprise,
  EpistemologyImpact,
  TheFirstQuestion,
} from './slides/Epistemology'
import { ThesisSlide } from './ThesisSlide'
import {
  DatabaseFeature,
  DbTestDrive,
  IntegratingViaDb,
  UnitVsIntegration,
  WhyAPyramid,
  NotUnitOrIntegration,
  YesFastRobustClear,
} from './slides/Databases'
import {
  ApiFeature,
  ApiTestDrive,
  BeTheChange,
} from './slides/ServiceApi'
import {
  HardIntegrationsFeature,
  HardIntegrationsTestDrive,
  ManualStepsFeature,
  ManualStepsProblem,
  ManualStepsWhatDo,
  EnvironmentSpecificProblem,
  UsualTricks,
  SameTechnique,
  SolidInTheWild,
} from './slides/HardIntegrations'
import { NoteOnTooling } from './slides/Tooling'

const slides = [
  <TableOfContents current={0}/>,
  <TableOfContents current={1}/>,
  <Hello index={0}/>,
  <Hello index={1}/>,
  <Hello index={2}/>,
  <Hello index={3}/>,
  <TalkIsNot index={0}/>,
  <TalkIsNot index={1}/>,
  <TalkIsNot index={2}/>,
  <TalkIsNot index={3}/>,
  <TalkIs index={0}/>,
  <TalkIs index={1}/>,
  <TalkIs index={2}/>,
  <TalkIs index={3}/>,
  <TableOfContents current={1}/>,
  <TableOfContents current={2}/>,
  <WeirdTangent/>,
  <Epistemology index={0}/>,
  <Epistemology index={1}/>,
  <Epistemology index={2}/>,
  <Epistemology index={3}/>,
  <Epistemology index={0}/>,
  <Epistemology index={4}/>,
  <Epistemology index={5}/>,
  <Epistemology index={6}/>,
  <Epistemology index={7}/>,
  <Epistemology index={8}/>,
  <Epistemology index={9}/>,
  <Epistemology index={0}/>,
  <EpistemologicalAttitude index={0}/>,
  <EpistemologicalAttitude index={1}/>,
  <TddStance index={0}/>,
  <TddStance index={1}/>,
  <TddStance index={2}/>,
  <ThesisSlide index={1}/>,
  <TableOfContents current={2}/>,
  <TableOfContents current={3}/>,
  <DatabaseFeature index={0}/>,
  <DatabaseFeature index={1}/>,
  <DatabaseFeature index={2}/>,
  <DbTestDrive index={0}/>,
  <DbTestDrive index={1}/>,
  <DbTestDrive index={2}/>,
  <GraphicSlide>db-feature-graphic-1.png</GraphicSlide>,
  <GraphicSlide>db-feature-graphic-2.png</GraphicSlide>,
  <GraphicSlide>db-feature-graphic-3.png</GraphicSlide>,
  <GraphicSlide>db-feature-graphic-4.png</GraphicSlide>,
  <GraphicSlide>db-feature-graphic-5.png</GraphicSlide>,
  <GraphicSlide>db-feature-graphic-6.png</GraphicSlide>,
  <GraphicSlide>db-feature-graphic-7.png</GraphicSlide>,
  <DbTestDrive index={3}/>,
  <DbTestDrive index={4}/>,
  <DbTestDrive index={5}/>,
  <DbTestDrive index={6}/>,
  <DatabaseFeature index={2}/>,
  <DatabaseFeature index={3}/>,
  <DatabaseFeature index={4}/>,
  <DatabaseFeature index={5}/>,
  <GraphicSlide>db-feature-graphic-8.png</GraphicSlide>,
  <GraphicSlide>db-feature-graphic-9.png</GraphicSlide>,
  <TableOfContents current={3}/>,
  <TableOfContents current={4}/>,
  <IntegratingViaDb/>,
  <GraphicSlide>db-integration-1.png</GraphicSlide>,
  <GraphicSlide>db-integration-2.png</GraphicSlide>,
  <GraphicSlide>db-integration-3.png</GraphicSlide>,
  <GraphicSlide>db-integration-1.png</GraphicSlide>,
  <GraphicSlide>db-integration-4.png</GraphicSlide>,
  <GraphicSlide>db-integration-5.png</GraphicSlide>,
  <GraphicSlide>db-integration-6.png</GraphicSlide>,
  <GraphicSlide>db-integration-5.png</GraphicSlide>,
  <GraphicSlide>db-integration-7.png</GraphicSlide>,
  <ThesisSlide index={0}>is it true that persistence is working?</ThesisSlide>,
  <ThesisSlide index={1}>is it true that persistence is working?</ThesisSlide>,
  <GraphicSlide>db-integration-6.png</GraphicSlide>,
  <ThesisSlide index={1}>is it true that persistence is working?</ThesisSlide>,
  <TableOfContents current={4}/>,
  <TableOfContents current={5}/>,
  <UnitVsIntegration index={0}/>,
  <UnitVsIntegration index={1}/>,
  // unit vs. integration 2
  <GraphicSlide>pyramid-1.png</GraphicSlide>,
  <GraphicSlide>pyramid-2.png</GraphicSlide>,
  <GraphicSlide>pyramid-3.png</GraphicSlide>,
  <GraphicSlide>pyramid-4.png</GraphicSlide>,
  <GraphicSlide>pyramid-5.png</GraphicSlide>,
  <GraphicSlide>pyramid-6.png</GraphicSlide>,
  <WhyAPyramid index={0}/>,
  <WhyAPyramid index={1}/>,
  <GraphicSlide>pyramid-1.png</GraphicSlide>,
  <GraphicSlide>pyramid-7.png</GraphicSlide>,
  <GraphicSlide>pyramid-9.png</GraphicSlide>,
  <GraphicSlide>pyramid-10.png</GraphicSlide>,
  <GraphicSlide>pyramid-11.png</GraphicSlide>,
  <GraphicSlide>pyramid-12.png</GraphicSlide>,
  <GraphicSlide>pyramid-13.png</GraphicSlide>,
  <GraphicSlide>pyramid-14.png</GraphicSlide>,
  <NotUnitOrIntegration/>,
  <YesFastRobustClear/>,
  <TableOfContents current={5}/>,
  <TableOfContents current={6}/>,
  <ApiFeature index={0}/>,
  <ApiFeature index={1}/>,
  <GraphicSlide>service-1.png</GraphicSlide>,
  <GraphicSlide>service-2.png</GraphicSlide>,
  <GraphicSlide>service-3.png</GraphicSlide>,
  <GraphicSlide>service-4.png</GraphicSlide>,
  <GraphicSlide>service-5.png</GraphicSlide>,
  <ThesisSlide index={0}>what should be true about the service?</ThesisSlide>,
  <ThesisSlide index={1}>what should be true about the service?</ThesisSlide>,
  <ApiTestDrive index={0}/>,
  <ApiTestDrive index={1}/>,
  <ApiTestDrive index={2}/>,
  <GraphicSlide>example-test-1.png</GraphicSlide>,
  <GraphicSlide>example-test-2.png</GraphicSlide>,
  <GraphicSlide>service-6.png</GraphicSlide>,
  <GraphicSlide>service-7.png</GraphicSlide>,
  <TableOfContents current={6}/>,
  <TableOfContents current={7}/>,
  <GraphicSlide>uncertain-1.png</GraphicSlide>,
  <GraphicSlide>uncertain-2.png</GraphicSlide>,
  <GraphicSlide>uncertain-3.png</GraphicSlide>,
  <TableOfContents current={7}/>,
  <TableOfContents current={8}/>,
  <BeTheChange index={0}/>,
  <BeTheChange index={1}/>,
  <BeTheChange index={2}/>,
  <BeTheChange index={3}/>,
  <TableOfContents current={8}/>,
  <TableOfContents current={9}/>,
  <HardIntegrationsFeature index={0}/>,
  <HardIntegrationsFeature index={1}/>,
  <HardIntegrationsTestDrive index={0}/>,
  <HardIntegrationsTestDrive index={1}/>,
  <HardIntegrationsTestDrive index={2}/>,
  <GraphicSlide>email-1.png</GraphicSlide>,
  <GraphicSlide>email-2.png</GraphicSlide>,
  <GraphicSlide>email-3.png</GraphicSlide>,
  <HardIntegrationsFeature index={2}/>,
  <HardIntegrationsFeature index={3}/>,
  <HardIntegrationsTestDrive index={3}/>,
  <GraphicSlide>email-4.png</GraphicSlide>,
  <GraphicSlide>email-5.png</GraphicSlide>,
  <GraphicSlide>email-6.png</GraphicSlide>,
  <GraphicSlide>email-7.png</GraphicSlide>,
  <GraphicSlide>email-8.png</GraphicSlide>,
  <ThesisSlide index={0}>is it true that customers get notified by email upon approval?</ThesisSlide>,
  <ThesisSlide index={1}>is it true that customers get notified by email upon approval?</ThesisSlide>,
  <TableOfContents current={9}/>,
  <TableOfContents current={10}/>,
  <ManualStepsFeature index={0}/>,
  <ManualStepsFeature index={1}/>,
  <ManualStepsFeature index={2}/>,
  <ManualStepsProblem/>,
  <ManualStepsWhatDo index={0}/>,
  <ManualStepsWhatDo index={1}/>,
  <GraphicSlide>manual-1.png</GraphicSlide>,
  <GraphicSlide>manual-2.png</GraphicSlide>,
  <GraphicSlide>manual-3.png</GraphicSlide>,
  <TableOfContents current={10}/>,
  <TableOfContents current={11}/>,
  <EnvironmentSpecificProblem index={0}/>,
  <EnvironmentSpecificProblem index={1}/>,
  <EnvironmentSpecificProblem index={2}/>,
  <UsualTricks/>,
  <GraphicSlide>environment-1.png</GraphicSlide>,
  <GraphicSlide>environment-2.png</GraphicSlide>,
  <GraphicSlide>environment-3.png</GraphicSlide>,
  <GraphicSlide>environment-4.png</GraphicSlide>,
  <GraphicSlide>environment-5.png</GraphicSlide>,
  <SameTechnique/>,
  <SolidInTheWild/>,
  <TableOfContents current={11}/>,
  <TableOfContents current={12}/>,
  <NoteOnTooling/>,
  <TableOfContents current={12}/>,
  <TableOfContents current={13}/>,
  <EpistemologyReprise index={0}/>,
  <EpistemologyReprise index={1}/>,
  <EpistemologyReprise index={2}/>,
  <EpistemologyImpact/>,
  <TheFirstQuestion index={0}/>,
  <TheFirstQuestion index={1}/>,
  <TheFirstQuestion index={2}/>,
  <TheFirstQuestion index={3}/>,
  <TableOfContents current={13}/>,
  <TableOfContents current={14}/>,
]

export { slides }
